# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WMCloverTest' do
pod 'WMTYCyclePagerView', :git => 'http://gitlab-cd.wm-motor.com/group-ase-1-app/wmtycyclepagerview.git', :tag => '0.1.0'
pod 'WMCloverSdk_Vendored', :git => 'http://gitlab-cd.wm-motor.com/group-ase-1-app/cloversdk.git', :branch => 'WMCloverSdk_Vendored'

end
